### ISSUE TITLE
Is it possible to retrieve FS.Files from a Meteor method rather than pub/sub

### ISSUE THREAD

**Issue by emmanuelbuah** [CollectionFS/Meteor-CollectionFS#580] opened 2015-03-04 00:52 UTC
I tested retrieval of uploaded files from a meteor method. The data arrives at the client as Fs.File array but methods such as isUploaded, isImage etc aren't working. Is pub/sub the only option to push uploaded Fs.File's to the client?

**Comment by rhyslbw** [comment] 2015-03-04 11:44
Can you share the code?

**Comment by emmanuelbuah** [comment] 2015-03-04 16:23
Sorry I forgot to include sample code. Below is a Meteor method that returns FS.Files to the client for display.

```

if(Meteor.isClient){
var imageStore = new FS.Store.FileSystem("images");
Images = new FS.Collection("images", {
  stores: [imageStore]
});
}

if(Meteor.isServer){
var imageStore = new FS.Store.FileSystem('images', {
    path: '~/dev/test/collectionFS/thumbnails'
});
Images = new FS.Collection("images", {
  stores: [imageStore],
  filter: {
    allow: {
      contentTypes: ['image/*']
    }
  }
});

  Metoer.methods({
    fetchImageFiles: function (fileIds) {
        this.unblock()
        check(fileIds, [String]);

        if (fileIds.length > 0) {
            return Images.find({
                _id: {
                    $in: fileIds
                }
            },{uploadedAt: -1}).fetch();
        }
        return [];
    }
});

}

//Use Meteor method fetchImageFiles in template like 
var fsfiles = new ReactiveVar()
 Template.files.helpers({
    fetchimages: function(imagefileIds){
      Meteor.call("fetchPostFiles", imagefileIds,function(error, files){
          fsfiles.set(files);
      });
      return fsfiles.get();
     },
}


```

**Comment by rhyslbw** [comment] 2015-03-06 09:38
Off the top of my head I can't think why the methods are not available as the pub/sub is just managing the synchronisation of the cursor, which the documents get transformed into FS.Files. Maybe setup a sample repo with this code to isolate the problem and provide less barriers for someone else to run it for more help. I notice you have a mismatched method call `fetchPostFiles`, although since you said you have the FS.Files on the client, I'm assuming this is just an error with your example.

**Comment by rhyslbw** [comment] 2015-03-06 09:51
… but the more important issue is why not just use a cursor? What's the use case?

Based on your original post, I was expecting the file to be returned based on an event, and since your helper has a declarative name (instead of `images`), it confused me.

**Comment by aldeed** [comment] 2015-03-06 14:49
We'll need a full reproduction app to investigate this. I think it probably should work, but I can't remember how the EJSON/transform stuff interacts.

**Comment by aldeed** [comment] 2015-03-06 14:50
Also of course make sure you do have the `cfs:ejson-file` package added, but it sounds like you do if you say they are coming across as FS.File instances.

**Comment by emmanuelbuah** [comment] 2015-03-06 15:45
Sorry guys. I had to do a copy/paste/edit for the sample code which didn't work as well. I will put together a repo.

**Comment by emmanuelbuah** [comment] 2015-03-06 15:56
@aldeed  Yeah. I do have cfs:ejson-file package added. @rhyslbw Use-case wise, this is helpful if you don't need files reactively (less work for meteor's data mergebox). The idea is to retrieve files adhoc on the client when they are needed without meteor reactively tracking the file.

**Comment by rhyslbw** [comment] 2015-03-08 11:56
@emmanuelbuah Sure makes sense. I'm a little confused over the use of a helper to do the fetching rather than using an event though. Will wait for the repo

**Comment by emmanuelbuah** [comment] 2015-03-08 15:48
@rhyslbw can you elaborate on what you mean by "use of event".

**Comment by rhyslbw** [comment] 2015-03-09 02:15
Let's see a full working example before continuing the conversation, as it will be easier to understand for us both.

**Comment by rhyslbw** [comment] 2015-03-16 23:24
I'll close this issue @emmanuelbuah, but feel free to reopen if you need to

**Closed by rhyslbw** 2015-03-16 23:24 UTC
