### ISSUE TITLE
does this plugin function in windows?

### ISSUE THREAD

**Issue by elkadiri-wd** [CollectionFS/Meteor-CollectionFS#913] opened 2016-01-18 22:42 UTC
plz tell me can this plugin function in windows? if so, why it gives me these errors while running:
 bumpversion.js:1:15: Unexpected token ILLEGAL
 publish.js:1:15: Unexpected token ILLEGAL
and in which version of meteor it can run?

thank you!

**Comment by mngkvn** [comment] 2016-01-24 05:10
It works on mine running windows and latest version of meteor. Did you double check your code ?

**Comment by harryadel** [comment] 2019-01-20 21:40
Hey there buddy, A bit late to the party but this issue was caused by `publish.js` and `bumpversion.js` where Meteor'd attempt to run them. It's fixed now.

**Closed by harryadel** 2019-01-20 21:40 UTC
